---
image: python:3

before_script:
  - python --version
  - pip install tox

stages:
  - verify
  - build
  - test
  - publish

build:
  stage: build
  script: python setup.py bdist_wheel

linting:
  stage: verify
  script: tox -e linters

docs:
  stage: publish
  script: tox -e docs,docs-linkcheck

coverage:
  stage: test
  script: tox -e cover

test-py27:
  stage: test
  image: python:2
  script: tox -e py27

test-py34:
  stage: test
  image: python:3.4
  script: tox -e py34

test-py35:
  stage: test
  image: python:3.5
  script: tox -e py35

test-py36:
  stage: test
  image: python:3.6
  script: tox -e py36
