---
image: python:3

before_script:
  - python --version
  - pip install tox

stages:
  - build
  - test

build:
  stage: build
  script: python setup.py bdist_wheel

test:
  stage: test
  script: tox
